In [1]:
#import libraries
import numpy as np
import pandas as pd
import plotly.express as px

In [2]:
#read the dataset
df=pd.read_csv('Coffe_sales.csv')
df

,hour_of_day,cash_type,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort,Date,Time
0,10,card,38.70,Latte,Morning,Fri,Mar,5,3,2024-03-01,10:15:50.520000
1,12,card,38.70,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,12:19:22.539000
2,12,card,38.70,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,12:20:18.089000
3,13,card,28.90,Americano,Afternoon,Fri,Mar,5,3,2024-03-01,13:46:33.006000
4,13,card,38.70,Latte,Afternoon,Fri,Mar,5,3,2024-03-01,13:48:14.626000
...,...,...,...,...,...,...,...,...,...,...,...
3542,10,card,35.76,Cappuccino,Morning,Sun,Mar,7,3,2025-03-23,10:34:54.894000
3543,14,card,35.76,Cocoa,Afternoon,Sun,Mar,7,3,2025-03-23,14:43:37.362000
3544,14,card,35.76,Cocoa,Afternoon,Sun,Mar,7,3,2025-03-23,14:44:16.864000
3545,15,card,25.96,Americano,Afternoon,Sun,Mar,7,3,2025-03-23,15:47:28.723000
3546,18,card,35.76,Latte,Night,Sun,Mar,7,3,2025-03-23,18:11:38.635000

In [3]:
#check the datatypes
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3547 entries, 0 to 3546
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   hour_of_day  3547 non-null   int64
 1   cash_type    3547 non-null   str
 2   money        3547 non-null   float64
 3   coffee_name  3547 non-null   str
 4   Time_of_Day  3547 non-null   str
 5   Weekday      3547 non-null   str
 6   Month_name   3547 non-null   str
 7   Weekdaysort  3547 non-null   int64
 8   Monthsort    3547 non-null   int64
 9   Date         3547 non-null   str
 10  Time         3547 non-null   str
dtypes: float64(1), int64(3), str(7)
memory usage: 304.9 KB

In [4]:
#modify datatype of Date column
df['Date']=pd.to_datetime(df['Date'])

In [5]:
#check for outliers and give a stat summary for numerical data
df.describe().round(2)

,hour_of_day,money,Weekdaysort,Monthsort,Date
count,3547.00,3547.00,3547.00,3547.00,3547
mean,14.19,31.65,3.85,6.45,2024-10-04 17:34:43.676346
min,6.00,18.12,1.00,1.00,2024-03-01 00:00:00
25%,10.00,27.92,2.00,3.00,2024-07-17 12:00:00
50%,14.00,32.82,4.00,7.00,2024-10-10 00:00:00
75%,18.00,35.76,6.00,10.00,2025-01-11 00:00:00
max,22.00,38.70,7.00,12.00,2025-03-23 00:00:00
std,4.23,4.88,1.97,3.50,NaN

In [6]:
#check for outliers and give a stat summary for categorical data
df.describe(include='string')

,cash_type,coffee_name,Time_of_Day,Weekday,Month_name,Time
count,3547,3547,3547,3547,3547,3547
unique,1,8,3,7,12,3547
top,card,Americano with Milk,Afternoon,Tue,Mar,10:15:50.520000
freq,3547,809,1205,572,494,1

## Best seller item is Americano with Milk
## best Time_of_Day is Afternoon
## best day tuesday
## best months is march

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.isna().sum()

hour_of_day    0
cash_type      0
money          0
coffee_name    0
Time_of_Day    0
Weekday        0
Month_name     0
Weekdaysort    0
Monthsort      0
Date           0
Time           0
dtype: int64

In [9]:
cols=df.columns

In [10]:
for c in cols:
    print(c)
    print(df[c].nunique())
    print(df[c].unique())
    print('-'*100)

hour_of_day
17
[10 12 13 15 16 18 19 11 14 17  9 20  8 22  7 21  6]
----------------------------------------------------------------------------------------------------
cash_type
1
<StringArray>
['card']
Length: 1, dtype: str
----------------------------------------------------------------------------------------------------
money
13
[38.7  28.9  33.8  24.   32.82 37.72 27.92 23.02 18.12 35.76 30.86 25.96
 21.06]
----------------------------------------------------------------------------------------------------
coffee_name
8
<StringArray>
[              'Latte',       'Hot Chocolate',           'Americano',
 'Americano with Milk',               'Cocoa',             'Cortado',
            'Espresso',          'Cappuccino']
Length: 8, dtype: str
----------------------------------------------------------------------------------------------------
Time_of_Day
3
<StringArray>
['Morning', 'Afternoon', 'Night']
Length: 3, dtype: str
----------------------------------------------------------------------------------------------------
Weekday
7
<StringArray>
['Fri', 'Sat', 'Sun', 'Mon', 'Tue', 'Wed', 'Thu']
Length: 7, dtype: str
----------------------------------------------------------------------------------------------------
Month_name
12
<StringArray>
['Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'Jan',
 'Feb']
Length: 12, dtype: str
----------------------------------------------------------------------------------------------------
Weekdaysort
7
[5 6 7 1 2 3 4]
----------------------------------------------------------------------------------------------------
Monthsort
12
[ 3  4  5  6  7  8  9 10 11 12  1  2]
----------------------------------------------------------------------------------------------------
Date
381
<DatetimeArray>
['2024-03-01 00:00:00', '2024-03-02 00:00:00', '2024-03-03 00:00:00',
 '2024-03-04 00:00:00', '2024-03-05 00:00:00', '2024-03-06 00:00:00',
 '2024-03-07 00:00:00', '2024-03-08 00:00:00', '2024-03-09 00:00:00',
 '2024-03-10 00:00:00',
 ...
 '2025-03-14 00:00:00', '2025-03-15 00:00:00', '2025-03-16 00:00:00',
 '2025-03-17 00:00:00', '2025-03-18 00:00:00', '2025-03-19 00:00:00',
 '2025-03-20 00:00:00', '2025-03-21 00:00:00', '2025-03-22 00:00:00',
 '2025-03-23 00:00:00']
Length: 381, dtype: datetime64[us]
----------------------------------------------------------------------------------------------------
Time
3547
<StringArray>
['10:15:50.520000', '12:19:22.539000', '12:20:18.089000', '13:46:33.006000',
 '13:48:14.626000', '15:39:47.726000', '16:19:02.756000', '18:39:03.580000',
 '19:22:01.762000', '19:23:15.887000',
 ...
 '15:57:58.183000', '16:26:59.766000', '17:53:35.942000', '19:16:52.727000',
 '10:07:11.278000', '10:34:54.894000', '14:43:37.362000', '14:44:16.864000',
 '15:47:28.723000', '18:11:38.635000']
Length: 3547, dtype: str
----------------------------------------------------------------------------------------------------

In [11]:
def clean_time(x):
    
    return x.split('.')[0]

In [12]:
df['Time']=df['Time'].apply(clean_time)

In [13]:
df['Time']

0       10:15:50
1       12:19:22
2       12:20:18
3       13:46:33
4       13:48:14
          ...
3542    10:34:54
3543    14:43:37
3544    14:44:16
3545    15:47:28
3546    18:11:38
Name: Time, Length: 3547, dtype: str

# Data Visualization Assignment

This assignment is based on a coffee shop transaction dataset.  

Dataset fields include:
- `hour_of_day`, `Time_of_Day`, `Weekday`, `Month_name`
- `coffee_name`, `cash_type`, `money`
- `Date`, `Time`

---

Note :  Apply EDA Steps first then answer the following questions

In [14]:
df.head()

,hour_of_day,cash_type,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort,Date,Time
0,10,card,38.7,Latte,Morning,Fri,Mar,5,3,2024-03-01,10:15:50
1,12,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,12:19:22
2,12,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,12:20:18
3,13,card,28.9,Americano,Afternoon,Fri,Mar,5,3,2024-03-01,13:46:33
4,13,card,38.7,Latte,Afternoon,Fri,Mar,5,3,2024-03-01,13:48:14

## Business Questions & Visualizations

### Q1. What is the total revenue per day of the week?
👉 Recommended visualization: **Bar chart**

In [15]:
# Write your visualization code here
total_revenue=df.groupby('Weekday')['money'].sum().sort_values(ascending=False).reset_index()
total_revenue

  Weekday     money
0     Tue  18168.38
1     Mon  17363.10
2     Fri  16802.66
3     Thu  16091.40
4     Wed  15750.46
5     Sat  14733.52
6     Sun  13336.06

In [16]:
! pip install --upgrade nbformat

Requirement already satisfied: nbformat in e:\anaconda3\an\envs\myenv\lib\site-packages (5.10.4)
Requirement already satisfied: fastjsonschema>=2.15 in e:\anaconda3\an\envs\myenv\lib\site-packages (from nbformat) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in e:\anaconda3\an\envs\myenv\lib\site-packages (from nbformat) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in e:\anaconda3\an\envs\myenv\lib\site-packages (from nbformat) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in e:\anaconda3\an\envs\myenv\lib\site-packages (from nbformat) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in e:\anaconda3\an\envs\myenv\lib\site-packages (from jsonschema>=2.6->nbformat) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in e:\anaconda3\an\envs\myenv\lib\site-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in e:\anaconda3\an\envs\myenv\lib\site-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in e:\anaconda3\an\envs\myenv\lib\site-packages (from jsonschema>=2.6->nbformat) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in e:\anaconda3\an\envs\myenv\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.5.1)

In [17]:
px.bar(data_frame=total_revenue,x='Weekday',y='money')

### Q2. What is the revenue trend over dates in the dataset?
👉 Recommended visualization: **Line chart**

In [18]:
daily_revenue = df.groupby('Date')['money'].sum().reset_index()

In [19]:
# Write your visualization code here
px.line(data_frame=daily_revenue,x='Date',y='Date')

### Q3. Which coffee type generates the most revenue?
👉 Recommended visualization: **Bar chart**

In [20]:
df.columns

Index(['hour_of_day', 'cash_type', 'money', 'coffee_name', 'Time_of_Day',
       'Weekday', 'Month_name', 'Weekdaysort', 'Monthsort', 'Date', 'Time'],
      dtype='str')

In [21]:
best_coffee=df.groupby('coffee_name')['money'].sum().reset_index()
best_coffee

           coffee_name     money
0            Americano  14650.26
1  Americano with Milk  24751.12
2           Cappuccino  17439.14
3                Cocoa   8521.16
4              Cortado   7384.86
5             Espresso   2690.28
6        Hot Chocolate   9933.46
7                Latte  26875.30

In [22]:
# Write your visualization code here
px.bar(data_frame=best_coffee,x='coffee_name',y='money')

### Q4. What is the percentage of each payment method (cash vs. card)?
👉 Recommended visualization: **Pie chart**

In [23]:
df.columns

Index(['hour_of_day', 'cash_type', 'money', 'coffee_name', 'Time_of_Day',
       'Weekday', 'Month_name', 'Weekdaysort', 'Monthsort', 'Date', 'Time'],
      dtype='str')

In [24]:
df['cash_type'].unique()

<StringArray>
['card']
Length: 1, dtype: str

In [25]:
# Write your visualization code here
px.pie(data_frame=df,names='cash_type')

### Q5. How does sales volume vary by hour of the day?
👉 Recommended visualization: **Histogram or Bar chart**

In [26]:
df.columns

Index(['hour_of_day', 'cash_type', 'money', 'coffee_name', 'Time_of_Day',
       'Weekday', 'Month_name', 'Weekdaysort', 'Monthsort', 'Date', 'Time'],
      dtype='str')

In [27]:
d=df.groupby('hour_of_day')['money'].size().reset_index()
d

    hour_of_day  money
0             6      5
1             7     88
2             8    235
3             9    242
4            10    328
5            11    283
6            12    241
7            13    225
8            14    225
9            15    236
10           16    278
11           17    237
12           18    218
13           19    229
14           20    169
15           21    195
16           22    113

In [28]:
# Write your visualization code here
px.bar(d, x='hour_of_day', y='money',labels={'money':'Sales_volume'})

### Q6. What is the average spending in each time of the day (Morning, Afternoon, Night)?
👉 Recommended visualization: **Bar Chart**

In [44]:
df.columns

Index(['hour_of_day', 'cash_type', 'money', 'coffee_name', 'Time_of_Day',
       'Weekday', 'Month_name', 'Weekdaysort', 'Monthsort', 'Date', 'Time'],
      dtype='str')

In [47]:
df_avg=df.groupby('Time_of_Day')['money'].mean().round(2).reset_index()
df_avg

  Time_of_Day  money
0   Afternoon  31.64
1     Morning  30.42
2       Night  32.89

In [48]:
# Write your visualization code here
px.bar(data_frame=df_avg,x='Time_of_Day',y='money')

### Q7. Which weekday has the highest average transaction value?
👉 Recommended visualization: **Bar chart**

In [49]:
df.columns

Index(['hour_of_day', 'cash_type', 'money', 'coffee_name', 'Time_of_Day',
       'Weekday', 'Month_name', 'Weekdaysort', 'Monthsort', 'Date', 'Time'],
      dtype='str')

In [70]:
df_2=df.groupby(['Weekday','Weekdaysort'])['money'].mean().round(2).reset_index().sort_values(by='money',ascending=False)
df_2.head(1)

  Weekday  Weekdaysort  money
1     Mon            1  31.92

In [71]:
# Write your visualization code here
px.bar(df_2,x='Weekday',y='money')

### Q8. Does Revenue differ from weekdays and weekends ?
👉 Recommended visualization: **bar chart**

In [72]:
df.columns

Index(['hour_of_day', 'cash_type', 'money', 'coffee_name', 'Time_of_Day',
       'Weekday', 'Month_name', 'Weekdaysort', 'Monthsort', 'Date', 'Time'],
      dtype='str')

In [74]:
df['Weekday'].unique()

<StringArray>
['Fri', 'Sat', 'Sun', 'Mon', 'Tue', 'Wed', 'Thu']
Length: 7, dtype: str

In [83]:
df['day_type'] = df['Weekday'].isin(['Sat','Sun']).map({True:'Weekend', False:'Weekday'})

In [85]:
df_type=df.groupby('day_type')['money'].sum().reset_index()
df_type

  day_type     money
0  Weekday  84176.00
1  Weekend  28069.58

In [86]:
px.bar(df_type,x='day_type',y='money')

### Q9. Top 5 coffee products contributing to revenue.
👉 Recommended visualization: **Horizontal bar chart**

In [87]:
df.columns

Index(['hour_of_day', 'cash_type', 'money', 'coffee_name', 'Time_of_Day',
       'Weekday', 'Month_name', 'Weekdaysort', 'Monthsort', 'Date', 'Time',
       'weekend', 'day_type'],
      dtype='str')

In [91]:
top=df.groupby('coffee_name')['money'].sum().reset_index().sort_values(by='money')
top

           coffee_name     money
5             Espresso   2690.28
4              Cortado   7384.86
3                Cocoa   8521.16
6        Hot Chocolate   9933.46
0            Americano  14650.26
2           Cappuccino  17439.14
1  Americano with Milk  24751.12
7                Latte  26875.30

In [92]:
# Write your visualization code here
px.bar(data_frame=top,x='coffee_name',y='money')

### Q10. What is the revenue contribution of each month?
👉 Recommended visualization: **Bar chart**

In [95]:
# Write your visualization code here
df.columns
df_month=df.groupby('Month_name')['money'].sum().reset_index().sort_values(by='money')
px.bar(data_frame=df_month,x='Month_name',y='money')

### Q11. Which coffee type is most popular during Morning, Afternoon, Night?
👉 Recommended visualization: **Grouped bar chart**

In [105]:
# Write your visualization code here
df.columns
df_time=df.groupby(['Time_of_Day','coffee_name'])['money'].count().reset_index()
df_time
px.bar(data_frame=df_time,x='Time_of_Day',y='money',color='coffee_name',barmode='group')

### Q12. Total number of transactions per payment type over weekdays.
👉 Recommended visualization: **Heatmap**

In [106]:
df.columns

Index(['hour_of_day', 'cash_type', 'money', 'coffee_name', 'Time_of_Day',
       'Weekday', 'Month_name', 'Weekdaysort', 'Monthsort', 'Date', 'Time',
       'weekend', 'day_type'],
      dtype='str')

In [111]:
n=df.groupby(['cash_type','Weekday'])['money'].count().reset_index()
n

  cash_type Weekday  money
0      card     Fri    532
1      card     Mon    544
2      card     Sat    470
3      card     Sun    419
4      card     Thu    510
5      card     Tue    572
6      card     Wed    500

In [ ]:
# Write your visualization code here
px.density_heatmap(n,x='cash_type',y='Weekday',z='money')
##The dataset contains only one payment method (card), so comparison between payment types is not possible.

### Q13. What is distribution of money spent per coffee type?
👉 Recommended visualization: **Box plot**

In [120]:
df.columns

Index(['hour_of_day', 'cash_type', 'money', 'coffee_name', 'Time_of_Day',
       'Weekday', 'Month_name', 'Weekdaysort', 'Monthsort', 'Date', 'Time',
       'weekend', 'day_type'],
      dtype='str')

In [123]:
# Write your visualization code here
px.box(data_frame=df,x='coffee_name',y='money')

### Q14. Which hour of day contributes most to revenue?
👉 Recommended visualization: **Bar chart**

In [124]:
df.columns

Index(['hour_of_day', 'cash_type', 'money', 'coffee_name', 'Time_of_Day',
       'Weekday', 'Month_name', 'Weekdaysort', 'Monthsort', 'Date', 'Time',
       'weekend', 'day_type'],
      dtype='str')

In [125]:
df['hour_of_day'].unique()

array([10, 12, 13, 15, 16, 18, 19, 11, 14, 17,  9, 20,  8, 22,  7, 21,  6])

In [133]:
hour=df.groupby('hour_of_day')['money'].sum().reset_index().sort_values(by='money',ascending=False)
hour

    hour_of_day     money
4            10  10198.52
10           16   9031.84
5            11   8453.10
13           19   7751.96
11           17   7659.76
9            15   7476.02
6            12   7419.62
3             9   7264.28
8            14   7173.80
12           18   7162.60
7            13   7028.76
2             8   7017.88
15           21   6397.94
14           20   5578.92
16           22   3635.16
1             7   2846.02
0             6    149.40

In [134]:
# Write your visualization code here
px.bar(data_frame=hour,x='hour_of_day',y='money')

### Q15. What is the overall percentage share of each coffee type in revenue?
👉 Recommended visualization: **Pie chart**

In [136]:
# Write your visualization code here
px.pie(data_frame=df,names='coffee_name',values='money')

### Q16. Is there a peak sales time in the day (hour-wise trend)?
👉 Recommended visualization: **Line chart**

In [139]:
df.columns

Index(['hour_of_day', 'cash_type', 'money', 'coffee_name', 'Time_of_Day',
       'Weekday', 'Month_name', 'Weekdaysort', 'Monthsort', 'Date', 'Time',
       'weekend', 'day_type'],
      dtype='str')

In [142]:
hour = df.groupby('hour_of_day')['money'].sum().reset_index()

In [143]:
# Write your visualization code here
px.line(data_frame=hour,x='hour_of_day',y='money')

### Q17. Compare revenue distribution between weekdays.
👉 Recommended visualization: **Box plot or Strip plot or violin plot**

In [144]:
df.columns

Index(['hour_of_day', 'cash_type', 'money', 'coffee_name', 'Time_of_Day',
       'Weekday', 'Month_name', 'Weekdaysort', 'Monthsort', 'Date', 'Time',
       'weekend', 'day_type'],
      dtype='str')

In [149]:
# Write your visualization code here
px.box(data_frame=df,x='Weekday',y='money')

### Q18. Which time of day has the highest number of coffee sold?
👉 Recommended visualization: **Bar chart**

In [150]:
df.columns

Index(['hour_of_day', 'cash_type', 'money', 'coffee_name', 'Time_of_Day',
       'Weekday', 'Month_name', 'Weekdaysort', 'Monthsort', 'Date', 'Time',
       'weekend', 'day_type'],
      dtype='str')

In [157]:
t = df.groupby('Time_of_Day')['coffee_name'].count().reset_index()
t

  Time_of_Day  coffee_name
0   Afternoon         1205
1     Morning         1181
2       Night         1161

In [160]:
# Write your visualization code here
px.bar(t, x='Time_of_Day', y='coffee_name',labels={'coffee_name':'number of orders'})

### Q19. How do sales patterns change between different payment methods across time of day?
👉 Recommended visualization: **Grouped bar chart**

In [166]:
sales = df.groupby(['Time_of_Day','cash_type'])['money'].sum().reset_index()
sales

  Time_of_Day cash_type     money
0   Afternoon      card  38130.04
1     Morning      card  35929.20
2       Night      card  38186.34

In [167]:
# Write your visualization code here
px.bar(
    sales,
    x='Time_of_Day',
    y='money',
    color='cash_type',
    barmode='group'
)

### Bonus Question (Search for cumsum function)
### Q20. Cumulative revenue trend across the dataset timeline.
👉 Recommended visualization: **Line chart with cumulative sum**

In [161]:
rev = df.groupby('Date')['money'].sum().reset_index()

In [162]:
rev['cumulative_revenue'] = rev['money'].cumsum()

In [165]:
# Write your visualization code here
px.line(rev,x='Date',y='cumulative_revenue',title='Cumulative Revenue Over Time')