In [1]:
import numpy as np
import pandas as pd
import plotly.express as px

# Bike Sharing Dataset: Column Explanations

This dataset contains hourly records of bike rentals along with corresponding weather and seasonal information. Below is a detailed breakdown of what each column represents:

| Column Name | Description | Data Type |
| :--- | :--- | :--- |
| **datetime** | The specific date and hour the data was recorded (e.g., `2011-01-01 00:00:00`). | Datetime |
| **season** | The current season of the year at the time of recording (e.g., `Spring`, `Winter`). | String |
| **holiday** | A binary indicator showing whether the day is a recognized public holiday (`1.0` = Yes, `0.0` = No). | Float (Boolean) |
| **workingday** | A binary indicator showing whether the day is a standard working day (`1.0` = Yes, `0.0` = No). A value of `0.0` usually indicates a weekend or holiday. | Float (Boolean) |
| **weather** | A categorical description of the weather condition during that hour (e.g., `Clear`, `Mist`). | String |
| **temp** | The actual temperature recorded during that hour (typically in Celsius). | Float |
| **humidity** | The relative humidity level as a percentage. | Float |
| **windspeed** | The recorded wind speed during that hour. | Float |
| **casual** | The count of bike rentals made by unregistered/casual users during that hour. | Integer |
| **registered** | The count of bike rentals made by registered/subscribed users during that hour. | Integer |
| **rented_bikes_count** | The total number of bikes rented during that hour. This is the sum of the `casual` and `registered` columns. | Integer |

---
*Note: Some rows contain missing values (represented as blanks/NaNs) which may require imputation or cleaning during exploratory data analysis.*

In [2]:
df=pd.read_csv('bikes.csv')
df

,datetime,season,holiday,workingday,weather,temp,humidity,windspeed,casual,registered,rented_bikes_count
0,2011-01-01 00:00:00,Spring,0.0,0.0,Clear,9.84,81.0,NaN,3,13,16
1,2011-01-01 01:00:00,Spring,0.0,0.0,NaN,9.02,80.0,0.0000,8,32,40
2,2011-01-01 02:00:00,Spring,0.0,0.0,Clear,9.02,NaN,0.0000,5,27,32
3,2011-01-01 03:00:00,Spring,0.0,0.0,Clear,9.84,75.0,0.0000,3,10,13
4,2011-01-01 04:00:00,NaN,0.0,0.0,Clear,NaN,75.0,NaN,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...
10881,2012-12-19 19:00:00,Winter,0.0,1.0,Clear,15.58,50.0,26.0027,7,329,336
10882,2012-12-19 20:00:00,Winter,0.0,1.0,NaN,14.76,NaN,NaN,10,231,241
10883,2012-12-19 21:00:00,NaN,0.0,1.0,Clear,13.94,61.0,15.0013,4,164,168
10884,2012-12-19 22:00:00,Winter,NaN,1.0,Clear,13.94,NaN,6.0032,12,117,129
10885,2012-12-19 23:00:00,Winter,0.0,1.0,Clear,13.12,66.0,8.9981,4,84,88

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10886 entries, 0 to 10885
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   datetime            10886 non-null  str
 1   season              10672 non-null  str
 2   holiday             10030 non-null  float64
 3   workingday          9388 non-null   float64
 4   weather             8746 non-null   str
 5   temp                8104 non-null   float64
 6   humidity            7462 non-null   float64
 7   windspeed           6820 non-null   float64
 8   casual              10886 non-null  int64
 9   registered          10886 non-null  int64
 10  rented_bikes_count  10886 non-null  int64
dtypes: float64(5), int64(3), str(3)
memory usage: 935.6 KB

In [5]:
df.describe().round(2)

,holiday,workingday,temp,humidity,windspeed,casual,registered,rented_bikes_count
count,10030.00,9388.00,8104.00,7462.00,6820.00,10886.00,10886.00,10886.00
mean,0.03,0.68,20.32,61.79,12.71,36.02,155.55,191.57
std,0.17,0.47,7.82,19.26,8.13,49.96,151.04,181.14
min,0.00,0.00,0.82,0.00,0.00,0.00,0.00,1.00
25%,0.00,0.00,13.94,47.00,7.00,4.00,36.00,42.00
50%,0.00,1.00,20.50,62.00,13.00,17.00,118.00,145.00
75%,0.00,1.00,26.24,77.00,17.00,49.00,222.00,284.00
max,1.00,1.00,41.00,100.00,57.00,367.00,886.00,977.00

In [6]:
df.describe(include='object')

C:\Users\HP\AppData\Local\Temp\ipykernel_14420\87514550.py:1: Pandas4Warning:

For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.

                   datetime  season weather
count                 10886   10672    8746
unique                10886       4       4
top     2011-01-01 00:00:00  Winter   Clear
freq                      1    2688    5793

In [7]:
df.duplicated().sum()

np.int64(0)

In [17]:
df.isna().sum()

datetime                 0
season                   0
holiday                834
workingday            1474
weather               2093
temp                  2732
humidity              3367
windspeed             3979
casual                   0
registered               0
rented_bikes_count       0
dtype: int64

In [18]:
df.isna().mean().round(4)*100

datetime               0.00
season                 0.00
holiday                7.81
workingday            13.81
weather               19.61
temp                  25.60
humidity              31.55
windspeed             37.28
casual                 0.00
registered             0.00
rented_bikes_count     0.00
dtype: float64

In [14]:
df.dropna(subset='season',inplace=True,ignore_index=True)

In [16]:
df

,datetime,season,holiday,workingday,weather,temp,humidity,windspeed,casual,registered,rented_bikes_count
0,2011-01-01 00:00:00,Spring,0.0,0.0,Clear,9.84,81.0,NaN,3,13,16
1,2011-01-01 01:00:00,Spring,0.0,0.0,NaN,9.02,80.0,0.0000,8,32,40
2,2011-01-01 02:00:00,Spring,0.0,0.0,Clear,9.02,NaN,0.0000,5,27,32
3,2011-01-01 03:00:00,Spring,0.0,0.0,Clear,9.84,75.0,0.0000,3,10,13
4,2011-01-01 06:00:00,Spring,0.0,0.0,Clear,NaN,NaN,0.0000,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...
10667,2012-12-19 18:00:00,Winter,0.0,1.0,NaN,15.58,NaN,23.9994,23,546,569
10668,2012-12-19 19:00:00,Winter,0.0,1.0,Clear,15.58,50.0,26.0027,7,329,336
10669,2012-12-19 20:00:00,Winter,0.0,1.0,NaN,14.76,NaN,NaN,10,231,241
10670,2012-12-19 22:00:00,Winter,NaN,1.0,Clear,13.94,NaN,6.0032,12,117,129
10671,2012-12-19 23:00:00,Winter,0.0,1.0,Clear,13.12,66.0,8.9981,4,84,88

In [19]:
#Fill missing values in columns (holiday, workingday, weather) with the mode

df['holiday']=df['holiday'].fillna(df['holiday'].mode)
df['workingday']=df['workingday'].fillna(df['workingday'].mode)
df['weather']=df['weather'].fillna(df['weather'].mode)

In [21]:
df.isna().sum()

datetime                 0
season                   0
holiday                  0
workingday               0
weather                  0
temp                  2732
humidity              3367
windspeed             3979
casual                   0
registered               0
rented_bikes_count       0
dtype: int64

In [22]:
#Fill missing values in column (humidity) with the median
df['humidity']=df['humidity'].fillna(df['humidity'].median())

In [23]:
df.isna().sum()

datetime                 0
season                   0
holiday                  0
workingday               0
weather                  0
temp                  2732
humidity                 0
windspeed             3979
casual                   0
registered               0
rented_bikes_count       0
dtype: int64

In [25]:
num_cols = df.select_dtypes(include= 'number').columns

In [26]:
#Fill missing values in columns (temp, windspeed) with the KNN imputer
from sklearn.impute import KNNImputer
knn = KNNImputer()
df[num_cols]=knn.fit_transform(df[num_cols])

In [27]:
df.isna().sum()

datetime              0
season                0
holiday               0
workingday            0
weather               0
temp                  0
humidity              0
windspeed             0
casual                0
registered            0
rented_bikes_count    0
dtype: int64